{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "import posix_ipc\n",
    "import time\n",
    "import os\n",
    "\n",
    "class IPCLock:\n",
    "    def __init__(self, name):\n",
    "        self.sem = posix_ipc.Semaphore(\n",
    "            name,\n",
    "            flags=posix_ipc.O_CREAT,  # 不存在则创建\n",
    "            # | posix_ipc.SEM_UNDO,\n",
    "            # mode=0o600,  # 权限：用户读写\n",
    "            mode=384,\n",
    "            initial_value=1,  # 初始为可用状态\n",
    "        )\n",
    "        self.owner_pid = None  # 记录持有者进程ID\n",
    "\n",
    "    def acquire(self, blocking=True, timeout=None):\n",
    "        \"\"\"获取锁核心逻辑\"\"\"\n",
    "        if blocking and timeout is not None:\n",
    "            return self._acquire_with_timeout(timeout)\n",
    "\n",
    "        acquired = self.sem.acquire(blocking)\n",
    "        if acquired:\n",
    "            self.owner_pid = os.getpid()\n",
    "        return acquired\n",
    "\n",
    "    def release(self):\n",
    "        \"\"\"释放锁并校验持有者\"\"\"\n",
    "        if self.owner_pid != os.getpid():\n",
    "            raise PermissionError(\"非持有进程禁止释放锁\")\n",
    "        self.sem.release()\n",
    "        self.owner_pid = None\n",
    "\n",
    "    def _acquire_with_timeout(self, timeout):\n",
    "        \"\"\"带超时的获取锁实现\"\"\"\n",
    "        end_time = time.time() + timeout\n",
    "        while time.time() < end_time:\n",
    "            if self.sem.acquire(blocking=False):\n",
    "                self.owner_pid = os.getpid()\n",
    "                return True\n",
    "            time.sleep(0.05)  # 避免CPU空转\n",
    "        return False\n",
    "\n",
    "    def __enter__(self):\n",
    "        self.acquire()\n",
    "        return self\n",
    "\n",
    "    def __exit__(self, *args):\n",
    "        self.release()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/node.py:187: UserWarning: Port 8787 is already in use.\n",
      "Perhaps you already have a cluster running?\n",
      "Hosting the HTTP server on port 52260 instead\n",
      "  warnings.warn(\n",
      "2025-02-28 15:36:28,051 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-06a9e2238d174d970b600cbec89d76b3\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-06a9e2238d174d970b600cbec89d76b3' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,055 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2a84c79009774a877af12d7031d6bfdd\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2a84c79009774a877af12d7031d6bfdd' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,061 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a397e4fcfeebf8f0212216a833775836\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a397e4fcfeebf8f0212216a833775836' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,065 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ae800c116732800c682efc433460a8a4\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ae800c116732800c682efc433460a8a4' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,068 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-67ac790eeacdba6eea832b5836a98cc6\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-67ac790eeacdba6eea832b5836a98cc6' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,078 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c0d809badbdfb2b53b7e4743e18714ac\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c0d809badbdfb2b53b7e4743e18714ac' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,084 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d59249f271a742c84b4f4c4a554effb0\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d59249f271a742c84b4f4c4a554effb0' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,086 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ccc13a9c020c8f5ab8816e7a9195c41f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ccc13a9c020c8f5ab8816e7a9195c41f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,101 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c52746ec12e5a2e040a2a508511a7fdd\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c52746ec12e5a2e040a2a508511a7fdd' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,106 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-135b951a5b901738af18efa123b991e5\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-135b951a5b901738af18efa123b991e5' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,112 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ddb6cf6183e16218b142545130babb24\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ddb6cf6183e16218b142545130babb24' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,121 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-5d6c80a66446aa51bbe128d27fdf7f77\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-5d6c80a66446aa51bbe128d27fdf7f77' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,140 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-cc952f6c49d2c978d3b3639bef786d4d\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-cc952f6c49d2c978d3b3639bef786d4d' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,143 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b6e447bf2171fbb9f76dc6f836ae44e2\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b6e447bf2171fbb9f76dc6f836ae44e2' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,146 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d1f37c4b8b7c06c9b0d9c90a597685a0\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d1f37c4b8b7c06c9b0d9c90a597685a0' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,155 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-78a7961e35ebad08a9615cceedce6f7b\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-78a7961e35ebad08a9615cceedce6f7b' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,179 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b70bc8608a63133ba7177c0ee409d070\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b70bc8608a63133ba7177c0ee409d070' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,184 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-1eec8c46ad911fbc81a3d71978bfa992\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-1eec8c46ad911fbc81a3d71978bfa992' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,194 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ffe39566a50b26c887727fdc245fd165\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ffe39566a50b26c887727fdc245fd165' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,203 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ac8ea6989e4fe68ceec867fa65e1d437\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ac8ea6989e4fe68ceec867fa65e1d437' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,207 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-8b6a55623bb63ccf14f324f6c2b2950b\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-8b6a55623bb63ccf14f324f6c2b2950b' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,213 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-5d4e151a7a149eda543b673a8ccf7a61\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-5d4e151a7a149eda543b673a8ccf7a61' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,241 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-6d78013749e7dde2e85aeb383bed5cf7\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-6d78013749e7dde2e85aeb383bed5cf7' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,244 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-26305b76e435b788bd6b4eb85ebf2d4a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-26305b76e435b788bd6b4eb85ebf2d4a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,250 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-501ffc01db77b47f42a73e9819c87f70\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-501ffc01db77b47f42a73e9819c87f70' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,269 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-e23c6cd59f96eba31f0953a290d91299\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-e23c6cd59f96eba31f0953a290d91299' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,276 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-74ce3a670c59f9e7ba04946c7d6e6a8c\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-74ce3a670c59f9e7ba04946c7d6e6a8c' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,283 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-521923d7b432efaf38a668d227916bb5\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-521923d7b432efaf38a668d227916bb5' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,292 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2e73bb8917477cc21048bb361378b5f3\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2e73bb8917477cc21048bb361378b5f3' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,314 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-9a52cbcc203dab850fb61af34dfdd64b\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-9a52cbcc203dab850fb61af34dfdd64b' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,316 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2b03f33f068f18fefc9ddad45e3b7ed1\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2b03f33f068f18fefc9ddad45e3b7ed1' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,321 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-0483e2c33cf0f207177fbae8578d7170\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-0483e2c33cf0f207177fbae8578d7170' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,342 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-f5767c96963f662e0cb5e1bdb56137e2\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-f5767c96963f662e0cb5e1bdb56137e2' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,343 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-68fad6fc66966406473804f27275373e\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-68fad6fc66966406473804f27275373e' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,347 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-13f35c5aa0ab1de03cfeae5170be4df1\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-13f35c5aa0ab1de03cfeae5170be4df1' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,356 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-27c92d44783282ca99610446c260e1ab\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-27c92d44783282ca99610446c260e1ab' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,372 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-1ef88e6db991b982e2517183ca378a6d\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-1ef88e6db991b982e2517183ca378a6d' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,379 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-27e4a1d2ccfb91cf3e2bed92af28f83c\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-27e4a1d2ccfb91cf3e2bed92af28f83c' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,393 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-1cde2be37f6ffe0ca55399a2e7dc6dd7\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-1cde2be37f6ffe0ca55399a2e7dc6dd7' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,400 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c8353bad0972416321706bad1548def0\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c8353bad0972416321706bad1548def0' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,409 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-8f4bebf940376759b55f308fced4c3ed\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-8f4bebf940376759b55f308fced4c3ed' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,416 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-0bd4acbe85f548c201573eed54e18aa6\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-0bd4acbe85f548c201573eed54e18aa6' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,420 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-1201f181d708cd519ad5abf6ab33ccd4\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-1201f181d708cd519ad5abf6ab33ccd4' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,426 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-fbbbe6fb225bfdcb64589e8bb2dcc568\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-fbbbe6fb225bfdcb64589e8bb2dcc568' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,430 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-944303e4d5659da30652823f964a361c\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-944303e4d5659da30652823f964a361c' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,452 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-736b6ff0899e47a812836b45cf9e63b6\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-736b6ff0899e47a812836b45cf9e63b6' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,459 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-18848f0937f3532c20063d9d7e74e003\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-18848f0937f3532c20063d9d7e74e003' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,463 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-cbb3287d8d33ff9986c8beead0cc50ab\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-cbb3287d8d33ff9986c8beead0cc50ab' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,489 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-e612e303665782869b84839d76577b39\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-e612e303665782869b84839d76577b39' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,504 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-318a5c2091d33da99e34c47e3d424730\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-318a5c2091d33da99e34c47e3d424730' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,507 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3a765c5b4553e7d23c46f71b157693bc\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3a765c5b4553e7d23c46f71b157693bc' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,513 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-e212ab4cf6986137604376aac31986e0\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-e212ab4cf6986137604376aac31986e0' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,524 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-90d12202535019b920d64d50435dc513\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-90d12202535019b920d64d50435dc513' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,532 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a1ad7078196015d321fcedffc0d2fecd\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a1ad7078196015d321fcedffc0d2fecd' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,538 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ade28ae404971c45d30d9d374b6f441a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ade28ae404971c45d30d9d374b6f441a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,558 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-880b1cf8abdc40dd8bd6c130152729d1\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-880b1cf8abdc40dd8bd6c130152729d1' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,562 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-f75efca8eb977f0db509d1f58c5a23a5\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-f75efca8eb977f0db509d1f58c5a23a5' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,567 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-7ff1555585bb92871f283d1ff6ca4bbd\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-7ff1555585bb92871f283d1ff6ca4bbd' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,590 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-06dcd71dbc56f166c7916cd2e9130f8b\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-06dcd71dbc56f166c7916cd2e9130f8b' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,592 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-32ab0e16f426ec884b2fda1870526021\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-32ab0e16f426ec884b2fda1870526021' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,598 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-cb57f792c21baff009a05558ae0a2e84\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-cb57f792c21baff009a05558ae0a2e84' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,602 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-9f8afcf0d2cac3dc9271bffff7fc7331\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-9f8afcf0d2cac3dc9271bffff7fc7331' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,613 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-f1163cd1d0b55aeddd27b2ce50d25d23\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-f1163cd1d0b55aeddd27b2ce50d25d23' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,638 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-455525154f6e38673d6c8876f08e4c62\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-455525154f6e38673d6c8876f08e4c62' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,642 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2801a17ca8da1eb3bc3a51dd7cd3e514\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2801a17ca8da1eb3bc3a51dd7cd3e514' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,646 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ce29372e6a2fc04a3444c9b54d0f1ad7\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ce29372e6a2fc04a3444c9b54d0f1ad7' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,651 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-26d9af17b09d32cffb4bcd74079ab318\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-26d9af17b09d32cffb4bcd74079ab318' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,680 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ebbb118cf77f70b79bf40164c859344b\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ebbb118cf77f70b79bf40164c859344b' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,680 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-304ab4b05f990b4fc9ed0b6ada9dea15\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-304ab4b05f990b4fc9ed0b6ada9dea15' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,703 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3e79bb48df15826c4df6b090a9381300\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3e79bb48df15826c4df6b090a9381300' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,712 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b1588dc483350267a67b7bd266c76a08\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b1588dc483350267a67b7bd266c76a08' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,716 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3240cb27e48c85432b81a8bcb9490158\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3240cb27e48c85432b81a8bcb9490158' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,717 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-8a766c638c7af3ceb85bc0245ad10f0f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-8a766c638c7af3ceb85bc0245ad10f0f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,728 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-baee69904a92170661bbaf58cd8ce051\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-baee69904a92170661bbaf58cd8ce051' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,734 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3b90e9da4990a60904cefd9944cf961e\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3b90e9da4990a60904cefd9944cf961e' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,737 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-48b5b27cb5eeff40a411f0602f242a4c\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-48b5b27cb5eeff40a411f0602f242a4c' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,750 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-7050111abf5582fdecd41d4ce86c7475\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-7050111abf5582fdecd41d4ce86c7475' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,767 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a584cc0237c0bbe34e46b89b1dbabb84\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a584cc0237c0bbe34e46b89b1dbabb84' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,769 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-78b2cd34df93795f360fa38fae8840fe\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-78b2cd34df93795f360fa38fae8840fe' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,774 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-150db4204845a5693904a245a9fe3dc3\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-150db4204845a5693904a245a9fe3dc3' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,778 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2d4014d7effb89b6eaf7cae4923a2440\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2d4014d7effb89b6eaf7cae4923a2440' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,785 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-4a757a1f1a1c0c8766200c4c05cd4e6c\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-4a757a1f1a1c0c8766200c4c05cd4e6c' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,808 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-5590c8d5ea7484ab4198d36d2e5cb258\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-5590c8d5ea7484ab4198d36d2e5cb258' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,811 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-50868c22e9807bff0027f3aaeadbce7b\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-50868c22e9807bff0027f3aaeadbce7b' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,816 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-6fffbd7adc639cf3e1d8c518789d7c3d\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-6fffbd7adc639cf3e1d8c518789d7c3d' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,819 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-0400b87f48d3876dbadba6276f1f4887\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-0400b87f48d3876dbadba6276f1f4887' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,842 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-35b87d54a085d7c1c9d11a95bb25cf10\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-35b87d54a085d7c1c9d11a95bb25cf10' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,848 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ce77dde1a3a658bf693979627bf97634\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ce77dde1a3a658bf693979627bf97634' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,849 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-01d4aa043c4fcc4d570b71c380e81802\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-01d4aa043c4fcc4d570b71c380e81802' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,863 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2e9c831e9f1dcb40777b12c6d9d81395\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2e9c831e9f1dcb40777b12c6d9d81395' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,869 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-edbb13d89ed6bd78d808a1c162e88615\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-edbb13d89ed6bd78d808a1c162e88615' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,886 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-20480464dcd4bb935a7b5be7a4bf1af5\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-20480464dcd4bb935a7b5be7a4bf1af5' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,892 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-4bec2234ea930e0d0afdc4dcf9a0f88d\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-4bec2234ea930e0d0afdc4dcf9a0f88d' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,894 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-aae21dc3d4f071d6d8a3cd632eb0f537\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-aae21dc3d4f071d6d8a3cd632eb0f537' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,914 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-4145c09cd6fbdcd3de5f31a01bc2b5a4\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-4145c09cd6fbdcd3de5f31a01bc2b5a4' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,916 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-8878c351d056b49c423795ca10b51954\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-8878c351d056b49c423795ca10b51954' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,919 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d887df0065f11b60d219501a84228215\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d887df0065f11b60d219501a84228215' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,934 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2bc149648969aac4e4bcfbc0f9a19326\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2bc149648969aac4e4bcfbc0f9a19326' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,937 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-5f7c0cabe184f2edd10310083f4615da\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-5f7c0cabe184f2edd10310083f4615da' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,945 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-aa123cf604026e58795f5f5b0b115ca7\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-aa123cf604026e58795f5f5b0b115ca7' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,978 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-53828872e1c772a5a5a727a2900f04d1\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-53828872e1c772a5a5a727a2900f04d1' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,983 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-f2eb79020f2c6c69f6a8591a8e0bb3c8\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-f2eb79020f2c6c69f6a8591a8e0bb3c8' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:28,992 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d7beb8c44533498177201ff1692ea3ed\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d7beb8c44533498177201ff1692ea3ed' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,014 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-8692c7b1cac6948aad8199c3ba6bb1bd\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-8692c7b1cac6948aad8199c3ba6bb1bd' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,015 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a72d6c9fc5e0e3a594dff34fdde3143a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a72d6c9fc5e0e3a594dff34fdde3143a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,019 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-93bc559e3f7e19a4c5f8a7f898ae8e43\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-93bc559e3f7e19a4c5f8a7f898ae8e43' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,030 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c192ef6e2590b9f1d5170d136742a836\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c192ef6e2590b9f1d5170d136742a836' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,039 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-fbc5098d627a3dab54a40145be94c217\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-fbc5098d627a3dab54a40145be94c217' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,047 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-1ca5e666eb7cf3c9fa248df8db1a0415\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-1ca5e666eb7cf3c9fa248df8db1a0415' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,049 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-38f680ec0e910db295f8e76a742cf394\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-38f680ec0e910db295f8e76a742cf394' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,064 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3f3f9f89f531e8d57cc3406957eff1de\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3f3f9f89f531e8d57cc3406957eff1de' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,068 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-51b61f1142a0f2e1d67e9b9e06919bd5\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-51b61f1142a0f2e1d67e9b9e06919bd5' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,071 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3ea33181089b2e4d2594e3c81bdac9a0\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3ea33181089b2e4d2594e3c81bdac9a0' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,097 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-bb52f1ef42bab215eb6672957a7e08f4\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-bb52f1ef42bab215eb6672957a7e08f4' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,105 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2ac64681448b94dde50775a49f832c0b\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2ac64681448b94dde50775a49f832c0b' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,112 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-0079794da8b92cb351cc5dd31b037402\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-0079794da8b92cb351cc5dd31b037402' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,128 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ba9cca4c0b9f9416af5e75e4418e0cb8\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ba9cca4c0b9f9416af5e75e4418e0cb8' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,131 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-9c57bb4709bcaad042b8802d7796cc01\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-9c57bb4709bcaad042b8802d7796cc01' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,379 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-6e13cd65693e2fb4be8b5324483b206f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-6e13cd65693e2fb4be8b5324483b206f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,385 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-67cfe7fd86289aa806d26762bd880780\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-67cfe7fd86289aa806d26762bd880780' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,403 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-34de7ecb888019dd42a00ab965e088b7\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-34de7ecb888019dd42a00ab965e088b7' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,405 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-902de0b16d7f20ddce0b5587985544c5\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-902de0b16d7f20ddce0b5587985544c5' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,411 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-38f16b06b19eee8df8ade90eacde5dc9\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-38f16b06b19eee8df8ade90eacde5dc9' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,432 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-056b71fcd6cb671015b166be9a918df4\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-056b71fcd6cb671015b166be9a918df4' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,437 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d4dd1f71ec77b4f80e0cf57f9deeef11\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d4dd1f71ec77b4f80e0cf57f9deeef11' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,441 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-21cc0912d5b214c8d01c89bfd887ca4b\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-21cc0912d5b214c8d01c89bfd887ca4b' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,444 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d6aa56c6a816ba7dd9f8cfd6888425c8\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d6aa56c6a816ba7dd9f8cfd6888425c8' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,452 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c318b48e12fdc00e6d41b0721e456f2a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c318b48e12fdc00e6d41b0721e456f2a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,464 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b39b3142b787e84adcb73e42f77fd87f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b39b3142b787e84adcb73e42f77fd87f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,469 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-94bd2fe508a59bfe630ba63479d8534d\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-94bd2fe508a59bfe630ba63479d8534d' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,477 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-14ecf5d707dbafa77ad6d0470dd0797a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-14ecf5d707dbafa77ad6d0470dd0797a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,485 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-80746ec24a8ee6796949a518b9b6c971\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-80746ec24a8ee6796949a518b9b6c971' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,501 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-85bcf20f0df19b20b5a949b91b180c29\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-85bcf20f0df19b20b5a949b91b180c29' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,535 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b6cfd6709b8ebea52ed95ee442d9995f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b6cfd6709b8ebea52ed95ee442d9995f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,537 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-cbef95201914a645b85e8a4d26b6bc4e\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-cbef95201914a645b85e8a4d26b6bc4e' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,540 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d1db92b4d616b61e891bbc0ebfcc1c3e\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d1db92b4d616b61e891bbc0ebfcc1c3e' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,545 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-893f802e0f2e71dd6b089a2a7ab7dea9\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-893f802e0f2e71dd6b089a2a7ab7dea9' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,556 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-33d0a0f34f48a346d8ea3e1e22be6f50\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-33d0a0f34f48a346d8ea3e1e22be6f50' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,561 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-08ca89ad55e6e5839b945fe9cea75ec3\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-08ca89ad55e6e5839b945fe9cea75ec3' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,568 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-f62fb1c8c830a2f513e99941ee134ea3\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-f62fb1c8c830a2f513e99941ee134ea3' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,581 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2a8780715d062ae83fec7e92688b8214\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2a8780715d062ae83fec7e92688b8214' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,590 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b944129f0762f98a04d571a33562653c\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b944129f0762f98a04d571a33562653c' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,594 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-741040a1cc5c32203a79cda666cc53b4\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-741040a1cc5c32203a79cda666cc53b4' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,596 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-89aa7d0121acea9378e84d1cf09bebaa\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-89aa7d0121acea9378e84d1cf09bebaa' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,620 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-580a3241faa3b7cd2d48461b48daaa75\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-580a3241faa3b7cd2d48461b48daaa75' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,626 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-5c88d025ead642bc8c3bf6e5dbbe757f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-5c88d025ead642bc8c3bf6e5dbbe757f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,647 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-f56e925cdd70969c4a2fbc46bb4f5b28\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-f56e925cdd70969c4a2fbc46bb4f5b28' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,649 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-0eaa5e077aef6e6294bdc53b5f36b499\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-0eaa5e077aef6e6294bdc53b5f36b499' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,653 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-0c90915ac1a7d00f5730ba956d0cd763\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-0c90915ac1a7d00f5730ba956d0cd763' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,670 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-dd3628892c7fe0a6646478c63c83e211\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-dd3628892c7fe0a6646478c63c83e211' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,675 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-fc36bb5bcc651f50e8829e9f1a76688f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-fc36bb5bcc651f50e8829e9f1a76688f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,680 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-95cd0b39d97f1c153a8a1a85ea7118da\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-95cd0b39d97f1c153a8a1a85ea7118da' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,701 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-efd08641441e65643853dc6286a3efae\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-efd08641441e65643853dc6286a3efae' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,709 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ee4cffad196f54ecc12d8d484300fc30\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ee4cffad196f54ecc12d8d484300fc30' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,712 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-1424f1fd47c4fc97258eba296713d614\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-1424f1fd47c4fc97258eba296713d614' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,722 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-da88da3de7f13d06ff83acaf584b8e61\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-da88da3de7f13d06ff83acaf584b8e61' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,736 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a2842e5d44201f44dd5e0692f9a72d7d\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a2842e5d44201f44dd5e0692f9a72d7d' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,750 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3d4db2c4931f935e786aec521fe854c0\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3d4db2c4931f935e786aec521fe854c0' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,752 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-61ce225ecc8c4544ff0be870a42c2db5\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-61ce225ecc8c4544ff0be870a42c2db5' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,757 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-8b41e6360dfcbb6517bb673cd7b5591f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-8b41e6360dfcbb6517bb673cd7b5591f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,761 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-35d8b47ceb210e842fb4fe042c5361de\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-35d8b47ceb210e842fb4fe042c5361de' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,779 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c6fb0c61568f1a432c1b1c3641615f67\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c6fb0c61568f1a432c1b1c3641615f67' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,801 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2be5c453f5a9297ceb180cdd09a0a474\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2be5c453f5a9297ceb180cdd09a0a474' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,803 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-560c1f4931853a8e58292feecb8872f3\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-560c1f4931853a8e58292feecb8872f3' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,811 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-885e3f3b287b9730ebe791ebd12ed51a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-885e3f3b287b9730ebe791ebd12ed51a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,818 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2cf17d8a4f9968d2645538a8806173c9\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2cf17d8a4f9968d2645538a8806173c9' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,832 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-13154b387d46aca7f9dd79a0145870de\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-13154b387d46aca7f9dd79a0145870de' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,833 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-105b8920768856d16d2d0fa7ff262dfd\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-105b8920768856d16d2d0fa7ff262dfd' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,854 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-7cc35ce666947ccb60ae8641f3d3b861\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-7cc35ce666947ccb60ae8641f3d3b861' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,860 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-58c4f7c7ff752bc7f707585a57e19ff2\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-58c4f7c7ff752bc7f707585a57e19ff2' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,879 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-67b16b35891dfb95070960ca0cd47319\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-67b16b35891dfb95070960ca0cd47319' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,885 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-4bca20d13f6f9ce77dcb8c1933369311\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-4bca20d13f6f9ce77dcb8c1933369311' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,889 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d11a364f6955b2711d80c1f686b9be87\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d11a364f6955b2711d80c1f686b9be87' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,892 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-539ca458258aa0582b129493a78088fc\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-539ca458258aa0582b129493a78088fc' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,908 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2e4acd25218db164e2434625ca2f4691\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2e4acd25218db164e2434625ca2f4691' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,921 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-7b40dda54dcd3a15f300b8c214c04309\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-7b40dda54dcd3a15f300b8c214c04309' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,932 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2c44b3a1a03a425f323d5e5767767953\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2c44b3a1a03a425f323d5e5767767953' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,933 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c2cc0b274b05501061fe04205a6d7082\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c2cc0b274b05501061fe04205a6d7082' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,966 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-86d31f5832b6e836befa8461d6351916\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-86d31f5832b6e836befa8461d6351916' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,968 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-50a3aa7fe3c155d20306ddd9af21a158\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-50a3aa7fe3c155d20306ddd9af21a158' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,978 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a5c66f3256093720dceb2f9cf5691581\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a5c66f3256093720dceb2f9cf5691581' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:29,983 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-907f6df11371491df9426e2c68f81a5a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-907f6df11371491df9426e2c68f81a5a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,010 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-29c3f3c1713ba77ede5c393c0fd34485\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-29c3f3c1713ba77ede5c393c0fd34485' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,028 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3bf15b9ea914ad0306fe6f9cd20f8b63\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3bf15b9ea914ad0306fe6f9cd20f8b63' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,032 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-7ceaafa769f67344dd5fb59632fff6c7\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-7ceaafa769f67344dd5fb59632fff6c7' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,034 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-6f43e7e61e16c3b130502346771eb951\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-6f43e7e61e16c3b130502346771eb951' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,047 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d26256f37a806b7eda98b2146f00ff1f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d26256f37a806b7eda98b2146f00ff1f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,061 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-9002db15126f1e86b93d294a6c953798\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-9002db15126f1e86b93d294a6c953798' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,075 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-2a5edde65cbdcf6ab31bb8dcc50815ff\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-2a5edde65cbdcf6ab31bb8dcc50815ff' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,077 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-8be7f14d6ea870d7fe8eba2005926df3\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-8be7f14d6ea870d7fe8eba2005926df3' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,082 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d3241b98186d6dc30a22f605a91a8b22\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d3241b98186d6dc30a22f605a91a8b22' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,113 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-1d670651081dc7c7ac66db6a66407c1f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-1d670651081dc7c7ac66db6a66407c1f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,115 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-4f1835a385b05b5b56db21893ca4f3cf\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-4f1835a385b05b5b56db21893ca4f3cf' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,118 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-81ef36ab309def8afbef2c9e58e1b7f8\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-81ef36ab309def8afbef2c9e58e1b7f8' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,137 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-8600e36220298c90f397606aeceb9df8\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-8600e36220298c90f397606aeceb9df8' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,148 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c483656d05306d284df263cf3f5ea270\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c483656d05306d284df263cf3f5ea270' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,149 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-f8225e1fa165a5f10467643df5b34d59\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-f8225e1fa165a5f10467643df5b34d59' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,165 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-54659e3ad7a0bff6741400f498fdd8da\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-54659e3ad7a0bff6741400f498fdd8da' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,170 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-5ebcea91e0e019ce82a75b1e0c2788e8\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-5ebcea91e0e019ce82a75b1e0c2788e8' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,174 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a83dbbe48eb4e8d1ce407b42d1e31ef6\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a83dbbe48eb4e8d1ce407b42d1e31ef6' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,179 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3bad48a326621b81decb632e3aaf3b94\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3bad48a326621b81decb632e3aaf3b94' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,202 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a6021cdb29924b6c4cd5fa23b59875fe\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a6021cdb29924b6c4cd5fa23b59875fe' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,208 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-9932d65861cac3860473cec9fe6234bb\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-9932d65861cac3860473cec9fe6234bb' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,213 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-0ce6dd973292469853f71c224af51f3d\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-0ce6dd973292469853f71c224af51f3d' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,227 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-904efc0600e2ec2528eb05056fc89a93\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-904efc0600e2ec2528eb05056fc89a93' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,251 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-be51729ff8288a8fb2d5305bbb924803\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-be51729ff8288a8fb2d5305bbb924803' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,256 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-1ba44f14d74eb954edf941a2342cbb69\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-1ba44f14d74eb954edf941a2342cbb69' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,260 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-5c19c09b5a4f601cb50c5baa30bb9ddb\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-5c19c09b5a4f601cb50c5baa30bb9ddb' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,265 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-cd4889123b94048d2421aa142a10f51c\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-cd4889123b94048d2421aa142a10f51c' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,290 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b0f427a610c2dc47e22c808de708aeb1\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b0f427a610c2dc47e22c808de708aeb1' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,299 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-94e23355e6b6f25698ccb7cdaa5f3b8f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-94e23355e6b6f25698ccb7cdaa5f3b8f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,302 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3ae5d62082dcf6754f332471b70ecf16\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3ae5d62082dcf6754f332471b70ecf16' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,303 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b8ab8085cdf028ba0da5d968a1f3f682\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b8ab8085cdf028ba0da5d968a1f3f682' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,326 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-9a8af42cc7657966da42afbb588af4d9\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-9a8af42cc7657966da42afbb588af4d9' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,333 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-0345f974ad708497b0eb3a80dfe136a4\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-0345f974ad708497b0eb3a80dfe136a4' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,373 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-becffad327bec70b00aaf358fce72976\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-becffad327bec70b00aaf358fce72976' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,377 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-51f4d5f1faed149a42655a0dfd40b2ee\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-51f4d5f1faed149a42655a0dfd40b2ee' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,381 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-81dc3945e79a2de0470bdd89e2589ddf\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-81dc3945e79a2de0470bdd89e2589ddf' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,391 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-83739e97f69ab371dffe7e2a91330384\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-83739e97f69ab371dffe7e2a91330384' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,400 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-bcb95a67e3b26b9cd7de5474dcc9e81a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-bcb95a67e3b26b9cd7de5474dcc9e81a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,401 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-85dfc9dd5f9b701a51299ca98d924e49\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-85dfc9dd5f9b701a51299ca98d924e49' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,409 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b5bcf1a161bcd31711ffc6a7300b59c4\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b5bcf1a161bcd31711ffc6a7300b59c4' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,422 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-9c8439ddcfb8912ba8374083f31e5e00\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-9c8439ddcfb8912ba8374083f31e5e00' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,430 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-ccd6fc93c8798ca865016b2e0e9fe048\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-ccd6fc93c8798ca865016b2e0e9fe048' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,434 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-219f26c96c7a72b1e62b12f83a2a0fe7\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-219f26c96c7a72b1e62b12f83a2a0fe7' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,442 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3699195b5fbee9c5fcd2238a5de50dac\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3699195b5fbee9c5fcd2238a5de50dac' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,458 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c95a6ceadcd59433ece5630fc0c2b189\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c95a6ceadcd59433ece5630fc0c2b189' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,474 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-3cb086c28be8b9ffdb08b96f81d35f98\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-3cb086c28be8b9ffdb08b96f81d35f98' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,489 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-4c860a8e3f9f02d7cacca00e01bd44aa\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-4c860a8e3f9f02d7cacca00e01bd44aa' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,493 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b2689e41c5508aa849b58295eb8b267f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b2689e41c5508aa849b58295eb8b267f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,518 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-54f04f889f973dc954e694ef1f476990\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-54f04f889f973dc954e694ef1f476990' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,522 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-97682a914c906bba790249f60067ae5f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-97682a914c906bba790249f60067ae5f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,536 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-cc372317feed69d82fe8eef0ecd095ba\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-cc372317feed69d82fe8eef0ecd095ba' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,537 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-f25483595e2f2e9909662017d8395849\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-f25483595e2f2e9909662017d8395849' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,538 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-36db66d5d9983912ec6655bc34159989\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-36db66d5d9983912ec6655bc34159989' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,545 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-fb08a980ca451cd5f78020ab6371ab6b\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-fb08a980ca451cd5f78020ab6371ab6b' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,560 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-808bcbadaf6799d8247c724a485cf87a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-808bcbadaf6799d8247c724a485cf87a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,562 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-39ddab5c00b5d264c0b8bc3c626dc26f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-39ddab5c00b5d264c0b8bc3c626dc26f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,567 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-79d7501c0c2f7a9f8b3ad6741d1be28f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-79d7501c0c2f7a9f8b3ad6741d1be28f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,571 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a7bb6de20a724a7d458cc0c8712cb48f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a7bb6de20a724a7d458cc0c8712cb48f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,599 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-c51d37af2c5f49e2bf1fdf63ea6f921c\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-c51d37af2c5f49e2bf1fdf63ea6f921c' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,600 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-722f999694da8d308cbb42ff274ff82a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-722f999694da8d308cbb42ff274ff82a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,605 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-b57012b3e3f963f8faffd019f66f0bd0\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-b57012b3e3f963f8faffd019f66f0bd0' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,622 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-a4d2a6732eb55dee54bb13d819fd8fa5\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-a4d2a6732eb55dee54bb13d819fd8fa5' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,634 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-d323b2e2588d91fe7260a60e548aead1\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-d323b2e2588d91fe7260a60e548aead1' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,643 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-94cbdf663b7b15618ae833a499d0e8ef\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-94cbdf663b7b15618ae833a499d0e8ef' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,658 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-4636acff53a6c3fe897ef2e3579ff2f1\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-4636acff53a6c3fe897ef2e3579ff2f1' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,664 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-209668fd564a79f2bc8987c68565db86\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-209668fd564a79f2bc8987c68565db86' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,668 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-42297245589a052a7cf32b790b321202\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-42297245589a052a7cf32b790b321202' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,688 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-60dd9b73936af957d03660e6f8a6533a\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-60dd9b73936af957d03660e6f8a6533a' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,694 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-458317bcf99db157eb35ffacf6ba588f\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-458317bcf99db157eb35ffacf6ba588f' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n",
      "2025-02-28 15:36:30,703 - distributed.worker - ERROR - Compute Failed\n",
      "Key:       dummy_task-abd8ecb0e673269d3f1e198c27938077\n",
      "State:     executing\n",
      "Task:  <Task 'dummy_task-abd8ecb0e673269d3f1e198c27938077' dummy_task(...)>\n",
      "Exception: \"BusyError('Semaphore is busy')\"\n",
      "Traceback: '  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/990653539.py\", line 23, in dummy_task\\n  File \"/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/ipykernel_87456/398838656.py\", line 22, in acquire\\n'\n",
      "\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[8], line 62\u001b[0m\n\u001b[1;32m     58\u001b[0m         i \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[1;32m     61\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;18m__name__\u001b[39m \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m__main__\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[0;32m---> 62\u001b[0m     \u001b[43mmain\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[0;32mIn[8], line 50\u001b[0m, in \u001b[0;36mmain\u001b[0;34m()\u001b[0m\n\u001b[1;32m     47\u001b[0m i \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[1;32m     48\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[1;32m     49\u001b[0m     futures\u001b[38;5;241m.\u001b[39mappend(\n\u001b[0;32m---> 50\u001b[0m         \u001b[43mclient\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msubmit\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m     51\u001b[0m \u001b[43m            \u001b[49m\u001b[43mdummy_task\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     52\u001b[0m \u001b[43m            \u001b[49m\u001b[43mi\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     53\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     54\u001b[0m     )\n\u001b[1;32m     55\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(futures) \u001b[38;5;241m>\u001b[39m n_workers \u001b[38;5;241m*\u001b[39m \u001b[38;5;241m2\u001b[39m:\n\u001b[1;32m     56\u001b[0m         _, undone \u001b[38;5;241m=\u001b[39m wait(futures, return_when\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFIRST_COMPLETED\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/client.py:2153\u001b[0m, in \u001b[0;36mClient.submit\u001b[0;34m(self, func, key, workers, resources, retries, priority, fifo_timeout, allow_other_workers, actor, actors, pure, *args, **kwargs)\u001b[0m\n\u001b[1;32m   2151\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m key \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m   2152\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m pure:\n\u001b[0;32m-> 2153\u001b[0m         key \u001b[38;5;241m=\u001b[39m funcname(func) \u001b[38;5;241m+\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m-\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m+\u001b[39m \u001b[43mtokenize\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   2154\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   2155\u001b[0m         key \u001b[38;5;241m=\u001b[39m funcname(func) \u001b[38;5;241m+\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m-\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m+\u001b[39m \u001b[38;5;28mstr\u001b[39m(uuid\u001b[38;5;241m.\u001b[39muuid4())\n",
      "File \u001b[0;32m~/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/dask/tokenize.py:76\u001b[0m, in \u001b[0;36mtokenize\u001b[0;34m(ensure_deterministic, *args, **kwargs)\u001b[0m\n\u001b[1;32m     74\u001b[0m     token \u001b[38;5;241m=\u001b[39m _ENSURE_DETERMINISTIC\u001b[38;5;241m.\u001b[39mset(ensure_deterministic)\n\u001b[1;32m     75\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 76\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_tokenize\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     77\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     78\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m token:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/dask/tokenize.py:34\u001b[0m, in \u001b[0;36m_tokenize\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     33\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_tokenize\u001b[39m(\u001b[38;5;241m*\u001b[39margs: \u001b[38;5;28mobject\u001b[39m, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs: \u001b[38;5;28mobject\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mstr\u001b[39m:\n\u001b[0;32m---> 34\u001b[0m     token: \u001b[38;5;28mobject\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[43m_normalize_seq_func\u001b[49m\u001b[43m(\u001b[49m\u001b[43margs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     35\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m kwargs:\n\u001b[1;32m     36\u001b[0m         token \u001b[38;5;241m=\u001b[39m token, _normalize_seq_func(\u001b[38;5;28msorted\u001b[39m(kwargs\u001b[38;5;241m.\u001b[39mitems()))\n",
      "File \u001b[0;32m~/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/dask/tokenize.py:152\u001b[0m, in \u001b[0;36m_normalize_seq_func\u001b[0;34m(seq)\u001b[0m\n\u001b[1;32m    150\u001b[0m _SEEN[\u001b[38;5;28mid\u001b[39m(seq)] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mlen\u001b[39m(_SEEN), seq\n\u001b[1;32m    151\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 152\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mtuple\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mmap\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m_inner_normalize_token\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mseq\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    153\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    154\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m _SEEN[\u001b[38;5;28mid\u001b[39m(seq)]\n",
      "File \u001b[0;32m~/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/dask/tokenize.py:146\u001b[0m, in \u001b[0;36m_normalize_seq_func.<locals>._inner_normalize_token\u001b[0;34m(item)\u001b[0m\n\u001b[1;32m    144\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(item, _IDENTITY_DISPATCH):\n\u001b[1;32m    145\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m item\n\u001b[0;32m--> 146\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mnormalize_token\u001b[49m\u001b[43m(\u001b[49m\u001b[43mitem\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/dask/utils.py:772\u001b[0m, in \u001b[0;36mDispatch.__call__\u001b[0;34m(self, arg, *args, **kwargs)\u001b[0m\n\u001b[1;32m    768\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m    769\u001b[0m \u001b[38;5;124;03mCall the corresponding method based on type of argument.\u001b[39;00m\n\u001b[1;32m    770\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m    771\u001b[0m meth \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdispatch(\u001b[38;5;28mtype\u001b[39m(arg))\n\u001b[0;32m--> 772\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mmeth\u001b[49m\u001b[43m(\u001b[49m\u001b[43marg\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/dask/tokenize.py:208\u001b[0m, in \u001b[0;36mnormalize_object\u001b[0;34m(o)\u001b[0m\n\u001b[1;32m    205\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m _normalize_dataclass(o)\n\u001b[1;32m    207\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 208\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_normalize_pickle\u001b[49m\u001b[43m(\u001b[49m\u001b[43mo\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    209\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:\n\u001b[1;32m    210\u001b[0m     _maybe_raise_nondeterministic(\n\u001b[1;32m    211\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mObject \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mo\u001b[38;5;132;01m!r}\u001b[39;00m\u001b[38;5;124m cannot be deterministically hashed. See \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    212\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhttps://docs.dask.org/en/latest/custom-collections.html#implementing-deterministic-hashing \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    213\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mfor more information.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    214\u001b[0m     )\n",
      "File \u001b[0;32m~/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/dask/tokenize.py:242\u001b[0m, in \u001b[0;36m_normalize_pickle\u001b[0;34m(o)\u001b[0m\n\u001b[1;32m    240\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    241\u001b[0m     out \u001b[38;5;241m=\u001b[39m mod\u001b[38;5;241m.\u001b[39mdumps(o, protocol\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m5\u001b[39m, buffer_callback\u001b[38;5;241m=\u001b[39mbuffers\u001b[38;5;241m.\u001b[39mappend)\n\u001b[0;32m--> 242\u001b[0m     \u001b[43mmod\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mloads\u001b[49m\u001b[43m(\u001b[49m\u001b[43mout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbuffers\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbuffers\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    243\u001b[0m     pik2 \u001b[38;5;241m=\u001b[39m hash_buffer_hex(out)\n\u001b[1;32m    244\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:\n",
      "File \u001b[0;32m~/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/cloudpickle/cloudpickle.py:393\u001b[0m, in \u001b[0;36m_builtin_type\u001b[0;34m(name)\u001b[0m\n\u001b[1;32m    389\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mtype\u001b[39m(v) \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28mtype\u001b[39m:\n\u001b[1;32m    390\u001b[0m         _BUILTIN_TYPE_NAMES[v] \u001b[38;5;241m=\u001b[39m k\n\u001b[0;32m--> 393\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_builtin_type\u001b[39m(name):\n\u001b[1;32m    394\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mClassType\u001b[39m\u001b[38;5;124m\"\u001b[39m:  \u001b[38;5;66;03m# pragma: no cover\u001b[39;00m\n\u001b[1;32m    395\u001b[0m         \u001b[38;5;66;03m# Backward compat to load pickle files generated with cloudpickle\u001b[39;00m\n\u001b[1;32m    396\u001b[0m         \u001b[38;5;66;03m# < 1.3 even if loading pickle files from older versions is not\u001b[39;00m\n\u001b[1;32m    397\u001b[0m         \u001b[38;5;66;03m# officially supported.\u001b[39;00m\n\u001b[1;32m    398\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mtype\u001b[39m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-02-28 15:36:32,735 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "2025-02-28 15:36:32,735 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "2025-02-28 15:36:32,737 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "2025-02-28 15:36:32,737 - distributed.nanny - ERROR - Worker process died unexpectedly\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "Process Dask Worker process (from Nanny):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/base_events.py\", line 685, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 985, in run\n",
      "    await worker.finished()\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/base_events.py\", line 685, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 985, in run\n",
      "    await worker.finished()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/core.py\", line 494, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/base_events.py\", line 685, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/core.py\", line 494, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 985, in run\n",
      "    await worker.finished()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/core.py\", line 494, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "asyncio.exceptions.CancelledError\n",
      "asyncio.exceptions.CancelledError\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/base_events.py\", line 685, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 985, in run\n",
      "    await worker.finished()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/base_events.py\", line 685, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/core.py\", line 494, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 985, in run\n",
      "    await worker.finished()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/core.py\", line 494, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "asyncio.exceptions.CancelledError\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/base_events.py\", line 685, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 985, in run\n",
      "    await worker.finished()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/core.py\", line 494, in finished\n",
      "    await self._event_finished.wait()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/locks.py\", line 212, in wait\n",
      "    await fut\n",
      "asyncio.exceptions.CancelledError\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 1023, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 1023, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 1023, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 1023, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 1023, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/process.py\", line 202, in _run\n",
      "    target(*args, **kwargs)\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/distributed/nanny.py\", line 1023, in _run\n",
      "    asyncio_run(run(), loop_factory=get_loop_factory())\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py\", line 123, in run\n",
      "    raise KeyboardInterrupt()\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "\n",
    "os.environ[\"PYTHONUNBUFFERED\"] = \"1\"\n",
    "\n",
    "import time\n",
    "import random\n",
    "from datetime import datetime\n",
    "\n",
    "from dask.distributed import (\n",
    "    Client,\n",
    "    LocalCluster,\n",
    "    get_worker,\n",
    "    wait,\n",
    "    Lock,\n",
    ")\n",
    "\n",
    "# NOTE: adjust the number of workers as needed. The more the sooner of crash.\n",
    "n_workers = 6\n",
    "\n",
    "\n",
    "def dummy_task(i):\n",
    "    lock = IPCLock(\"/my_lock\")\n",
    "    if lock.acquire(blocking=False, timeout=2):\n",
    "        try:\n",
    "            print(\n",
    "                f'{datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")} worker#{get_worker().name} acquired lock and completed task #{i}'\n",
    "            )\n",
    "        finally:\n",
    "            lock.release()\n",
    "    else:\n",
    "        print(\n",
    "            f'{datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")} worker#{get_worker().name} lock not acquired due to timeout. task #{i}'\n",
    "        )\n",
    "\n",
    "    return None\n",
    "\n",
    "\n",
    "def main():\n",
    "    cluster = LocalCluster(\n",
    "        n_workers=n_workers,\n",
    "        threads_per_worker=1,\n",
    "        processes=True,\n",
    "    )\n",
    "    client = Client(cluster)\n",
    "\n",
    "    futures = []\n",
    "    i = 0\n",
    "    while True:\n",
    "        futures.append(\n",
    "            client.submit(\n",
    "                dummy_task,\n",
    "                i,\n",
    "            )\n",
    "        )\n",
    "        if len(futures) > n_workers * 2:\n",
    "            _, undone = wait(futures, return_when=\"FIRST_COMPLETED\")\n",
    "            futures = list(undone)\n",
    "        i += 1\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv_3.12.2",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
